name: polyominos
channels:
  - cogsci
  - defaults
  - conda-forge
dependencies:
  - ncurses
  - numpy
  - numpy-base
  - openssl
  - pip
  - pygame
  - python
  - readline
  - setuptools
  - sqlite
  - tbb
  - tbb4py
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
